### ISSUE TITLE
Multiple API example

### ISSUE THREAD

**Issue by Gaaaabor** [VeloxDB/VeloxDB#2]
Hey,

I'm working on an opensource Db connector for Akka.Net and VeloxDb, but struggling with creation of multiple APIs and I don't know what's wrong.
I keep getting the error: [26D4] [Error] API  uses a name that is already used by another API."

Which is strange because I've named my APIs explicitly. (could be a cache?)

Already checked the docs and couldn't find any part which prohibits it.
Is it possible to create multiple APIs in one Db or I miss something?

My code:

https://github.com/Gaaaabor/Akka.Persistence.VeloxDb/blob/master/Akka.Persistence.VeloxDb.Db/JournalItemApi.cs
https://github.com/Gaaaabor/Akka.Persistence.VeloxDb/blob/master/Akka.Persistence.VeloxDb/Journal/IJournalItemApi.cs

https://github.com/Gaaaabor/Akka.Persistence.VeloxDb/blob/master/Akka.Persistence.VeloxDb.Db/SnapshotStoreItemApi.cs
https://github.com/Gaaaabor/Akka.Persistence.VeloxDb/blob/master/Akka.Persistence.VeloxDb/Snapshot/ISnapshotStoreItemApi.cs

**Comment by Gaaaabor** [comment]
Meanwhile I found the root cause.

The error message is not for the API's name but for the methods in:
https://github.com/VeloxDB/VeloxDB/blob/8ae34a2d3fb970ea7d91c01090014b135f32de96/VeloxDB.Common/Protocol/DbAPIHost.cs#L175

I think this could be Method name in the error instead of ApiName, because it can be misleading.

**Comment by nikola-moraca** [comment]
You are definitely right. It should be:
throw DbAPIDefinitionException.CreateOperationNameDuplicate(operName).

**Comment by Gaaaabor** [comment]
If I understand correctly, the API-s cant share the same method name, right?
I think on for example:

FooApi.GetUsers()
BarApi.GetUsers()

Because in line https://github.com/VeloxDB/VeloxDB/blob/8ae34a2d3fb970ea7d91c01090014b135f32de96/VeloxDB.Common/Protocol/DbAPIHost.cs#L174
only the method's name is checked but not with the class that contains it?

**Comment by nikola-moraca** [comment]
No, its only inside a  single API. operNames are the names of API operations inside a single API.

**Comment by Gaaaabor** [comment]
Thanks!
